### PR TITLE
Update qpe.cpp

### PR DESCRIPTION
**Pull request by ryanhill1**
Fix rotation gate numbering to reflect R_k = [[1, 0], [0, e^(2pi*i / 2^k)]] for the indicie k.

### CODE REVIEW

**Comment by vsoftco** [comment]
Can you please make sure the circuit drawn at the beginning of the example is correct? Didn't really have time to check, but let's make sure the Rs are as defined. BTW, where did you take the circuit from? If N&C, can add a note. Thanks!

**Comment by ryanhill1** [comment]
Yes, the circuit drawn at the beginning is correct. With this update, the labeling of the R_k's in the output will match the labeling of the R_k's in the drawing. I produced the drawing myself. But as a whole, this example was inspired by the Qiskit QPE tutorial: https://qiskit.org/textbook/ch-algorithms/quantum-phase-estimation.html

**Comment by vsoftco** [comment]
When I run I get
`...`
`
R1(2, 1) H1
`
`R2(3, 2) R2(2, 2) H2`
`...`

which is not the same as the drawn circuit. Can you please double check the output and the circuit drawn at the beginning of the example? Also `R2(2,2)` should not be correct (same ctrl and target). Thanks!

**Comment by ryanhill1** [comment]
Sorry, you're right, I changed the "m" instead of the first "j" in line 76. My new pull request should be correct.

**Pull request closed without merging**
