### PR TITLE
improve performance of multiidx2n

### PR DESCRIPTION
**Pull request by enum-class**
Improve performance of multiidx2n function, which exist in the hot pass.

### CODE REVIEW

**Comment by enum-class** [comment]
Hi @vsoftco, is there anything else that needs to be addressed for the p.r ?

**Comment by jimlambert** [comment]
Thanks Saman, looks good just doing some testing on our end, we’ll be in touch shortly!

From: Saman ***@***.***>
Date: Monday, May 6, 2024 at 8:23 AM
To: softwareQinc/qpp ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [softwareQinc/qpp] improve performance of multiidx2n (PR #173)

Hi @vsoftco<https://github.com/vsoftco>, is there anything else that needs to be addressed for the p.r ?

**Review by vsoftco — CHANGES_REQUESTED** [review]
Can you please re-write L113 as `part_prod *= dims[numdims-1];`? Other than that, all looks good, I'll merge it once the modification. Thanks!

**Comment by enum-class** [comment]
@vsoftco @jimlambert thanks, I have done it

**Pull request merged**
