### PR TITLE
created quantum phase estimation program for examples dir

### PR DESCRIPTION
**Pull request by ryanhill1**

### CODE REVIEW

**Comment by vsoftco** [comment]
Nice, thanks! The line `std::cout << ">> Measurement result q0: " << res << '\n';` should be "...q" << i<<": ", right?

**Comment by ryanhill1** [comment]
> Nice, thanks! The line `std::cout << ">> Measurement result q0: " << res << '\n';` should be `"...q" << i<<": "`, right?

Yes, it should. Good catch

**Review by vsoftco — APPROVED** [review]

**Comment by ryanhill1** [comment]
It seems that this last commit failed the `random.cpp` unit test for `qpp_rand.RealMatrix` line 148: `EXPECT_NEAR(0, average, 1); // very likely`. The message reads, `The difference between 0 and average is 1.0221263420644076, which exceeds 1`. Do you know what caused this failure?

**Comment by vsoftco** [comment]
@ryanhill1 That's expected sometimes. It's a randomness test, which sometime can fail. I restarted the build.

**Comment by ryanhill1** [comment]
Got it. Thanks, love the program!

**Comment by vsoftco** [comment]
Great thanks!!

**Pull request merged**
