### PR TITLE
Add missing matrix registration in QCircuit::measureV

### PR DESCRIPTION
**Pull request by antoine-bussy**
After using ```QCircuit::measureV```, ```QEngine::execute``` crashes with exception ```"qpp::measure(): Object has zero size!"```.
This seems to be cause by the basis matrix not being registered in the hash table.

Also added a simplified Rotation method that uses ```std::array``` instead of ```std::vector```.

### CODE REVIEW

**Review by vsoftco — APPROVED** [review]
Darn!!! I just didn't use this function at all in QCircuit, and completely missed that I forgot to register the matrix... Thanks!!

And indeed `std::array<double, 3>` is the perfect type for `Rn`.

**Comment by antoine-bussy** [comment]
You're welcome!
BTW I misplaced the include of ```<array>```. You might want to move it after the header guard later.
I guess I caught it because I haven't understood yet why it's better to measure in the Z basis rather than in the Id2 basis 😅

**Comment by vsoftco** [comment]
Thanks! As a convention, I don't keep headers in the `.hpp` files, but only include them once in `qpp.h`, as all header files are interconnected and I treat them all as a single unit.

**Comment by vsoftco** [comment]
> 
> 
> You're welcome!
> BTW I misplaced the include of `<array>`. You might want to move it after the header guard later.
> I guess I caught it because I haven't understood yet why it's better to measure in the Z basis rather than in the Id2 basis 😅

`measureV(gt.Id2)` is exactly the same as `measureZ`. The latter is used for convenience, as most of the time one measures in the computational basis (Z basis).

**Pull request merged**
